[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/api/*"
  to = "https://backendrgpl.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "https://backendrgpl.onrender.com/api/auth/login"
  status = 200
  force = true
